### ISSUE TITLE
Vaurca Cloning

### ISSUE THREAD

**Issue by SilverTalismen** [Aurorastation/Aurora#835]
Cloning with no organs but alive still somehow, Have cloned before but this time Had no organs

**Comment by skull132** [comment]
Possibly related to #828 . I need to remember how organs were managed.

**Comment by Skysabre321** [comment]
This brings up a major issue, Vauca cloning. They are so heavily mechanised that you would need basically a new species of Vaurca implemented to properly represent an un-augmented bug, and it brings the issue, if a Bound is cloned, is the clone unbound? Unless your mind is canonically something that leaves your body and enters your new one.

It brings a lot of issues, and it may be better to have the Vaurca to be set as "unclonable", Due to the nature of their bodies are most likely an extremely limited knowledge of their physiology.

**Comment by SilverTalismen** [comment]
I would say make it so you can brain transfer them into the proto Vaurca and then shock the body with the paddles to revive them? bound would stay bound and unbound would be unbound since they would have the same brain

**Comment by skull132** [comment]
Vaurca cloning is fixed for the time being (they are not able to be cloned). Discussion on what mechanics shall be used to replicate the gameplay effect in a fashion appropriate to Vaurca lore should probably be taken over to the suggestions forums.
